watir/watir-webdriver

- lib/watir-webdriver/locators/text_field_locator.rb
Current deprecation warning is short-circuited if located by id.
> provide textarea deprecation warning when element located by id

- lib/watir-webdriver/elements/element.rb
- lib/watir-webdriver/elements/iframe.rb
- lib/watir-webdriver/elements/select.rb
- lib/watir-webdriver/locators/element_locator.rb
- lib/watir-webdriver/wait.rb
- spec/element_spec.rb
Update references to ObsoleteElementError exception with the [new name] (https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/error.rb#L191) - StaleElementReferenceError for consistency
> update error names

- lib/watir-webdriver/browser.rb
- lib/watir-webdriver/elements/element.rb
- lib/watir-webdriver/elements/iframe.rb
If the driver context is inside a frame, it will fail on an assert_not_stale call, even if the element is actually there. Specs for this are here - https://github.com/watir/watirspec/pull/50
> ensure driver is in desired context to check for stale elements

- lib/watir-webdriver/attribute_helper.rb
- lib/watir-webdriver/elements/button.rb
- lib/watir-webdriver/elements/checkbox.rb
- lib/watir-webdriver/elements/element.rb
- lib/watir-webdriver/elements/file_field.rb
- lib/watir-webdriver/elements/form.rb
- lib/watir-webdriver/elements/iframe.rb
- lib/watir-webdriver/elements/option.rb
- lib/watir-webdriver/elements/radio.rb
- lib/watir-webdriver/elements/select.rb
- lib/watir-webdriver/user_editable.rb
- spec/always_locate_spec.rb
- spec/element_spec.rb
Element#assert_not_stale as currently implemented is useful for more static interactions with the page (refreshes and the like)
With more dynamic updates to the DOM, we sometimes have elements going stale between the #assert_not_stale call and the wire call that uses the element object.
These updates: 
1) Reduce the number of places where wire calls are made directly and push the implementation to the Element superclass where possible. 
2) Re-look up the element if it is stale, but still exists. If it passes the #assert_not_stale, then becomes stale, there is no reason to not retry instead of letting the test fail.
> Improve stale element handling

- lib/watir-webdriver/elements/element.rb
- spec/always_locate_spec.rb
This essentially changes always_locate to locate_when_necessary
The Watir.always_locate? setting currently conflates whether to cache and whether to fail when stale. [Reading through](http://watirmelon.com/2011/08/02/watir-webdriver-obselete-element-error/) the [background conversations](https://groups.google.com/forum/#!topic/watir-general/WhwpPvzHWmM/discussion) for implementing always_locate, it seems the important issue is that it not throw an exception when the element goes stale. With my test suite I saw a performance improvement of 15-20%. So, huge performance bump without affecting the desired behavior.
> Only re-look up elements when they aren't stale

- lib/watir-webdriver/exception.rb
- spec/browser_spec.rb
- spec/element_locator_spec.rb
- spec/spec_helper.rb
Also cleans up unused exceptions.
Related to watir/watirspec#61
> Use full path to exceptions in specs

- lib/watir-webdriver/elements/iframe.rb
For #299 we supported selectors for frames by doing a lookup of all the frame elements and all the frame elements matching the provided selector. I'm hitting a race condition where the frame hasn't finished loading on the page. With the current code the all_elements variable returns a size of zero, but the ElementCollection#elements call returns with a size of one.  
The subset of matching iframes should never be greater than all the iframes on the page.
> addresses race conditions with slow loading frames

- watir-webdriver.gemspec
Looks like a new update to this gem might be breaking our tests. Doing a PR to verify, will un-comment this line as the fix if this PR fails on Travis.
> Fix issue with rest-client update with running watir-spec

- lib/watir-webdriver/browser.rb
- lib/watir-webdriver/elements/element.rb
- spec/element_spec.rb
- spec/html/removed_element.html
#286 fixed the issue with #211, but introduced a bug with a race condition for stale elements with multiple hierarchy elements. When the elements go stale, the current code does not re-lookup the top level element when Watir.always_locate? == true, and does not reset the entire chain of elements (only the top element) when Watir.always_locate? == false. This fixes the submitted specs and @bret made my previous implementation more readable and made the previous assert_not_stale better parallel the behavior or assert_exist.
> Ensure not stale

- lib/watir-webdriver/locators/button_locator.rb
- lib/watir-webdriver/locators/element_locator.rb
- lib/watir-webdriver/locators/text_area_locator.rb
- spec/element_locator_spec.rb
Regexp selectors are highly inefficient as they require additional round
trip requests (to retrieve attribute values) for each element that
matches the simplified selector. This optimization limits the number of
requests needed by converting leading and trailing runs of literals in
each regular expression to to an xpath `contains` predicate. Note that
problematic regular expressions such as case insensitive patterns and
those containing '|' are not converted.
> Optimize regexp selectors when using xpath

- CHANGES.md
- lib/watir-webdriver.rb
- lib/watir-webdriver/after_hooks.rb
- lib/watir-webdriver/alert.rb
- lib/watir-webdriver/browser.rb
- lib/watir-webdriver/checkers.rb
- lib/watir-webdriver/elements/element.rb
- lib/watir-webdriver/elements/form.rb
Related to #351 
This is a quick and working solution to the problem of sharing checkers between. We can actually implement it way easier by passing `Watir::Browser` instance to `Watir::Alert` constructor and just calling `browser#run_checkers` later.
I kinda like this solution more because it remove checkers responsibility from `Watir::Browser` and make API more OO. Though, this means we have to deprecate current API and update it watir-classic too.
@titusfortner @jarmo @jkotests Please take a look. If you don't like this solution, I can easily revert and forget about it.
Specs are in https://github.com/watir/watirspec/pull/67
> Extract Checkers into separate API and run them after alert ok/close

- lib/watir-webdriver/browser.rb
This gives us:
Stale Element Protection. I hit this race condition working with watirspecs on my mac yesterday.
and
Context Protection. Current code will give different responses depending on which frame has recently been pointed to. Browser#text should always return top level, and IFrame#text needs to be used if text from a nested context is desired.
> get browser text like text of any other element

- lib/watir-webdriver/elements/select.rb
Our site has some drop downs with a ridiculous number of options in them (over 1,000, don't ask).
The current implementation requires a complete iteration of all options more than once to return a response.
This implementation will return a true response as soon as it finds it, and doesn't add much overhead for iterating through everything to give a false response if it isn't found.
> performance improvement for large drop downs

- lib/watir-webdriver/browser.rb
I was going through the Selenium code with @abaird and noticed that there was a lot more chatter than I expected for the navigation call. I don't think we need to go through the extra overhead of the url method here when we already have the uri that gets returned anyway. 
We just called the /url endpoint, and there is no scenario where we aren't in the top browsing context with an active browser after this. 
The current code Does a /window call then a /windows call then a /frame call then finally another /url call.
> saves 4 wire calls for each navigation

- Rakefile
```rake all_browsers``` works to run all applicable tests for all browsers applicable for the operating system. I'm not a rakefile expert, so this probably can be improved.
> rake task to run specs with all browsers

- lib/watir-webdriver/elements/button.rb
- lib/watir-webdriver/elements/element.rb
- lib/watir-webdriver/elements/input.rb
- lib/watir-webdriver/elements/select.rb
- spec/element_spec.rb
Since #363, we have an inconsistent behavior of `#enabled?` across different elements:
1. `Element#enabled?` returns `false` if element is not present.
2. `Button#enabled?` raises `UnknownObjectException` if element is not present (same for other `Element` children implementations).
To me, it makes perfect sense to raise `UnknownObjectException` if element is not present, so I've decided to that it would be better to define the correct behavior on `Element` class and remove all children implementations (though watirspecs are still subject to be removed).
I don't want to push this directly to master without notifying @Rodney-QAGeek and @titusfortner. Since this method is used by `#when_enabled` decorator, it might break somethings for you guys. However, I believe the correct solution is to …
> Element#enabled? should raise when element does not exist

- spec/element_spec.rb
- spec/implementation.rb
Selenium no longer supports any Firefox browsers with Native Events. The one spec that was blocked for synthetic events works just fine on Firefox 45. IE supports the toggle, but we don't have any tests for which it applies.
> native events not needed

- lib/watir-webdriver/elements/iframe.rb
There is no reason to use an atom here, when when we can make the same selenium call. Also, no reason not to implement text here as well.
> FramedDriver methods match browser methods

- lib/watir-webdriver/elements/element.rb
- spec/always_locate_spec.rb
- spec/element_spec.rb
Looking at how these tests were stubbed, I noticed some issues.
1) Result of element going stale between assert exists and action should be the same as other times an element goes stale - (UnknownObjectException not StaleElementReferenceError)
2) Removing an element from the DOM isn't accurately modeling an element going stale, so I don't even know what that is attempting to test.
3) Due to performance issues we no longer check for staleness from the top. We check the bottom element and re-look everything up if that one is stale.
> fix issues with stale elements

- CHANGES.md
- lib/watir-webdriver/version.rb
- watir-webdriver.gemspec
My Proposed Plan:
1. Merge this
2. Deploy the final watir-webdriver gem on rubygems
3. Rename existing watir github repo to watir_meta & update the Readme about it being deprecated; it does not need a version change or deploy to rubygems, just a commit for the Readme
4. Rename watir-webdriver github repo to watir
5. Merge #395 
6. Add Note to Readme and gemspec of watir-classic that it is no longer actively maintained with a recommendation to `require watir`and deploy to rubygems
7. Steaks for everyone!
> final release as watir-webdriver
